name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Install Qt Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev build-essential

    - name: Configure Project with Qmake
      run: qmake MiniCTViewer.pro

    - name: Compile Project
      run: make -j$(nproc)
